# Generated by Django 2.0 on 2019-12-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='census',
            name='provincia',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
