# Generated by Django 2.0 on 2019-12-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_auto_20191216_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10, null=True),
        ),
    ]
