# Generated by Django 2.0 on 2020-01-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0003_auto_20191217_2049'),
        ('census', '0002_auto_20200103_1227'),
        ('census', '0002_auto_20191226_1908'),
	('census', '0002_auto_20191216_1512'),
    ]

    operations = [
    ]
